
import MiscFrames.About;
import MiscFrames.Tutorial;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ddmareo
 */
public class finalproject extends javax.swing.JFrame {

    /**
     * Creates new form finalproject
     */
    public finalproject() {
        setIconImage();
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroup = new javax.swing.ButtonGroup();
        ImageIcon icon=new ImageIcon(getClass().getResource("Background.png"));
        java.awt.Image img=icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g)
            {
                g.drawImage(img,0,0,getWidth(),
                    getHeight(),this);
            }
        };
        jLabel2 = new javax.swing.JLabel();
        portraitchoice = new javax.swing.JRadioButton();
        landscapechoice = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        outputString = new javax.swing.JTextField();
        convertnowButton = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        logoProgram = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        miscMenu = new javax.swing.JMenu();
        tutorialMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image To PDF Converter");
        setName("Image To PDF Converter"); // NOI18N

        Desktop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Which one do you prefer for the output?");

        buttongroup.add(portraitchoice);
        portraitchoice.setText("Portrait");
        portraitchoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portraitchoiceActionPerformed(evt);
            }
        });

        buttongroup.add(landscapechoice);
        landscapechoice.setText("Landscape");
        landscapechoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landscapechoiceActionPerformed(evt);
            }
        });

        jLabel3.setText("What do you want to name the output file?");

        convertnowButton.setFont(new java.awt.Font("HomepageBaukasten Bold", 0, 36)); // NOI18N
        convertnowButton.setText("CONVERT NOW");
        convertnowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertnowButtonActionPerformed(evt);
            }
        });

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Select the output file type:");

        logoProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiscFrames/Logo.png"))); // NOI18N

        Desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(portraitchoice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(landscapechoice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(outputString, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(convertnowButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(combobox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(logoProgram, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertnowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(DesktopLayout.createSequentialGroup()
                                .addComponent(portraitchoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(landscapechoice))
                            .addComponent(jLabel3)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputString, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(logoProgram)))
                .addContainerGap())
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logoProgram)
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(portraitchoice)
                            .addComponent(landscapechoice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(convertnowButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenu);

        menuBar.add(fileMenu);

        miscMenu.setText("Misc");
        miscMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscMenuActionPerformed(evt);
            }
        });

        tutorialMenu.setText("Tutorial");
        tutorialMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialMenuActionPerformed(evt);
            }
        });
        miscMenu.add(tutorialMenu);

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        miscMenu.add(aboutMenu);

        menuBar.add(miscMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        
    }//GEN-LAST:event_fileMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void portraitchoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portraitchoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portraitchoiceActionPerformed

    private void convertnowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertnowButtonActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setMultiSelectionEnabled(true);
    fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif"));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File[] selectedFiles = fileChooser.getSelectedFiles();
        String outputFileName = outputString.getText() + ".pdf";
        PdfConverter pdfConverter = new PdfConverter(outputFileName);
        
        if (portraitchoice.isSelected()) {
            pdfConverter.setOrientation(true);
        } else if (landscapechoice.isSelected()) {
            pdfConverter.setOrientation(false);
        } else {
            JOptionPane.showMessageDialog(null, "Please select one of the orientations!", "Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            pdfConverter.convert(selectedFiles);
            JOptionPane.showMessageDialog(this, "Conversion completed successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Conversion failed: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_convertnowButtonActionPerformed

    private void tutorialMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialMenuActionPerformed
        Tutorial frm = new Tutorial();
        Desktop.add(frm);
        frm.setVisible(true);
        
    }//GEN-LAST:event_tutorialMenuActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        About frm = new About();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void miscMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miscMenuActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void landscapechoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landscapechoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landscapechoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalproject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.ButtonGroup buttongroup;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JButton convertnowButton;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton landscapechoice;
    private javax.swing.JLabel logoProgram;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu miscMenu;
    private javax.swing.JTextField outputString;
    private javax.swing.JRadioButton portraitchoice;
    private javax.swing.JMenuItem tutorialMenu;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
    }
}
